#!/usr/bin/env bash
#
# One-command deploy of the AI Governance Workshop onto a customer workspace.
#
#   ./deploy.sh -p <cli-profile> -w <warehouse-id> -c <uc-catalog> [-g <group>]
#
# Does the whole sequence, in order, and checks its own work:
#   1. builds the frontend (if Node is available; skipped if dist/ is already built)
#   2. deploys the bundle  -> Lakebase instance, UC schema, the app
#   3. reads back the app's service principal and re-deploys so UC grants attach to it
#   4. prints the two `system` GRANT statements an account admin must run
#   5. starts the app and polls /api/health until it reports ok
#
# Safe to re-run: every step is idempotent.

set -euo pipefail

PROFILE="" WAREHOUSE="" CATALOG="" GROUP="users" SCHEMA="ai_governance_workshop"

usage() {
  sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-1}"
}

while getopts "p:w:c:g:s:h" opt; do
  case "$opt" in
    p) PROFILE=$OPTARG ;;
    w) WAREHOUSE=$OPTARG ;;
    c) CATALOG=$OPTARG ;;
    g) GROUP=$OPTARG ;;
    s) SCHEMA=$OPTARG ;;
    h) usage 0 ;;
    *) usage 1 ;;
  esac
done

[[ -n $PROFILE && -n $WAREHOUSE && -n $CATALOG ]] || {
  echo "ERROR: -p (profile), -w (warehouse id) and -c (catalog) are all required." >&2
  usage 1
}

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[33m    ! %s\033[0m\n' "$1"; }
ok()   { printf '\033[32m    ✓ %s\033[0m\n' "$1"; }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

cd "$(dirname "$0")"
DBX=(databricks -p "$PROFILE")

# --------------------------------------------------------------------- preflight
step "Checking prerequisites"
command -v databricks >/dev/null || die "the databricks CLI is not on PATH."

"${DBX[@]}" current-user me >/dev/null 2>&1 \
  || die "profile '$PROFILE' cannot authenticate. Try: databricks auth login -p $PROFILE"
ok "authenticated as $("${DBX[@]}" current-user me --output json | python3 -c 'import json,sys; print(json.load(sys.stdin)["userName"])')"

"${DBX[@]}" warehouses get "$WAREHOUSE" >/dev/null 2>&1 \
  || die "warehouse '$WAREHOUSE' not found. List them with: databricks warehouses list -p $PROFILE"
ok "warehouse $WAREHOUSE exists"

# The bundle creates the SCHEMA but not the CATALOG — a missing catalog otherwise fails
# mid-deploy with a less obvious message.
"${DBX[@]}" catalogs get "$CATALOG" >/dev/null 2>&1 \
  || die "catalog '$CATALOG' not found. Create it, or pick another with: databricks catalogs list -p $PROFILE"
ok "catalog $CATALOG exists"

# --------------------------------------------------------------------- frontend
step "Pinning catalog/schema into the app config"
# The app reads catalog/schema from config/workshop.yaml, and the bundle takes them as
# variables. Write the deploy-time values into a local override so the two can never
# disagree — that mismatch previously meant the bundle created one schema while the app
# wrote to another. workshop.local.yaml is gitignored and takes precedence.
python3 - "$CATALOG" "$SCHEMA" <<'PY'
import sys, pathlib, yaml
catalog, schema = sys.argv[1], sys.argv[2]
base = pathlib.Path("config/workshop.yaml")
cfg = yaml.safe_load(base.read_text()) or {}
cfg.setdefault("catalog", {})
cfg["catalog"]["name"] = catalog
cfg["catalog"]["schema"] = schema
out = pathlib.Path("config/workshop.local.yaml")
out.write_text(
    "# GENERATED by deploy.sh — do not edit. Mirrors the catalog/schema passed to\n"
    "# `bundle deploy` so the app and the bundle cannot disagree. Edit\n"
    "# config/workshop.yaml for everything else; re-running deploy.sh regenerates this.\n"
    + yaml.safe_dump(cfg, sort_keys=False)
)
print(f"    wrote config/workshop.local.yaml ({catalog}.{schema})")
PY
ok "app and bundle agree on $CATALOG.$SCHEMA"

step "Building the frontend"
# Only build when we have to. A prebuilt dist/ plus no source changes is the common case,
# and rebuilding needlessly means an npm install that fails on any host without registry
# access — which would otherwise block a deploy for no reason.
build_frontend() {
  ( cd frontend
    if [[ -f package-lock.json ]]; then npm ci --silent || npm install --silent
    else npm install --silent; fi
    npm run build >/dev/null )
}

if [[ ! -f frontend/dist/index.html ]]; then
  command -v npm >/dev/null || die \
    "frontend/dist is missing and npm is not installed. Install Node 20+, or build dist on
    another machine (cd frontend && npm install && npm run build) and copy it in."
  echo "    No prebuilt dist — building (needs npm registry access)…"
  build_frontend || die \
    "the frontend build failed. If this host has no npm registry access, build dist
    elsewhere and copy frontend/dist/ in, then re-run."
  ok "built frontend/dist"
elif [[ -n $(find frontend/src frontend/index.html frontend/package.json \
              -newer frontend/dist/index.html 2>/dev/null) ]]; then
  warn "frontend sources are newer than dist — rebuilding."
  build_frontend || die "the frontend build failed; frontend/dist is stale."
  ok "rebuilt frontend/dist"
else
  ok "frontend/dist is up to date"
fi

# --------------------------------------------------------------------- deploy
VARS=(--var="warehouse_id=$WAREHOUSE" --var="catalog=$CATALOG"
      --var="schema=$SCHEMA" --var="workshop_group=$GROUP")

step "Validating the bundle"
"${DBX[@]}" bundle validate -t dev "${VARS[@]}" >/dev/null \
  || die "bundle validation failed — see the output above."
ok "bundle config is valid"

step "Deploying the bundle (Lakebase instance, UC schema, app)"
# First pass: the app does not exist yet, so neither does its service principal. The grant
# defaults to the deploying user (a principal Terraform can resolve); pass 2 re-points it.
"${DBX[@]}" bundle deploy -t dev "${VARS[@]}"
ok "bundle deployed"

step "Granting the app's service principal access to $CATALOG.$SCHEMA"
APP_SP=$("${DBX[@]}" apps get ai-governance-workshop --output json \
          | python3 -c 'import json,sys; print(json.load(sys.stdin).get("service_principal_client_id") or "")')
[[ -n $APP_SP ]] || die "could not read the app's service principal id."
ok "app service principal: $APP_SP"

# Second pass: now that the principal is known, re-deploy so the schema grant attaches.
"${DBX[@]}" bundle deploy -t dev "${VARS[@]}" --var="app_service_principal_id=$APP_SP"
ok "granted USE_SCHEMA, CREATE_FUNCTION, EXECUTE, SELECT, MODIFY on $CATALOG.$SCHEMA"

# --------------------------------------------------------------------- start
step "Starting the app"
"${DBX[@]}" bundle run ai_governance_workshop_app -t dev "${VARS[@]}" >/dev/null || true

APP_URL=$("${DBX[@]}" apps get ai-governance-workshop --output json \
           | python3 -c 'import json,sys; print(json.load(sys.stdin).get("url") or "")')
ok "app URL: ${APP_URL:-<unknown>}"

# --------------------------------------------------------------------- system grants
step "Remaining manual step: two system-schema grants (account admin)"
cat <<SQL
    Run these as an account or metastore admin. Without them the seven telemetry steps
    report "action needed" — every other step, including the routing ROI, still works.

    GRANT USE CATALOG ON CATALOG system TO \`$APP_SP\`;
    GRANT USE SCHEMA, SELECT ON SCHEMA system.ai_gateway TO \`$APP_SP\`;
    GRANT USE SCHEMA, SELECT ON SCHEMA system.access     TO \`$APP_SP\`;
SQL

step "Verifying"
echo "    Waiting for the app to report healthy (up to ~3 min)…"
for _ in $(seq 1 18); do
  HEALTH=$("${DBX[@]}" apps get ai-governance-workshop --output json 2>/dev/null \
            | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("app_status") or {}).get("state",""))' 2>/dev/null || true)
  [[ $HEALTH == RUNNING ]] && break
  sleep 10
done

if [[ ${HEALTH:-} == RUNNING ]]; then
  ok "app is RUNNING"
  echo
  echo "    Open $APP_URL and confirm the Introduction page loads."
  echo "    If a step reports a config problem, GET /api/health names exactly what is unset."
else
  warn "app is not RUNNING yet (state: ${HEALTH:-unknown})."
  warn "Check logs with: databricks apps logs ai-governance-workshop -p $PROFILE"
fi

printf '\n\033[1mDone.\033[0m Deploy is idempotent — re-run this script any time.\n'
